### ISSUE TITLE
Planet doesn't reposition when restarting a level

### ISSUE THREAD

**Issue by bochelord** [radicalgraphics/IterRad#1]
When the level is restarted, once you play 1 game, the planet appears too close to the left. Hence taking way less to fly through the screen. This is due the resolutions, that are different for each device. We need to pass the planet and probably all the reposition elements, except the GUI, through the resolution manager again...

**Comment by bochelord** [comment]
Apparently we NEED to create a Reset mechanism for the DeepSpace image to avoid errors when the player restarts the game for the second time...

**Comment by Leunam** [comment]
Using application.loadlevel(application.loadedlevel) fix this issue.
