### ISSUE TITLE
Bg Background needs to wrap around properly

### ISSUE THREAD

**Issue by bochelord** [radicalgraphics/IterRad#4]
The graphic needs to be aligned with the other side of it to avoid these errors:

![bg_overlay_wrap](https://cloud.githubusercontent.com/assets/3027503/6234709/4eeca0e0-b6dd-11e4-9818-a964d326f9b4.jpg)

**Comment by Aetherwrath** [comment]
Sprite Updated. Now tileable. Fixed and updated in GitHub
