### ISSUE TITLE
[Graphic] - Single hexagonal structure issue

### ISSUE THREAD

**Issue by Leunam** [radicalgraphics/IterRad#5]
Description:
The middle_bg graphic doesn't look nice if we use only one structure at a time. The picture composition has hexagonal panels and then a kind of concrete column to hold these hexagons, there should be anothe graphic without the concrete part.

Suggestion:
Please create a new graphic without this kind of concrete element.
![structure-style](https://cloud.githubusercontent.com/assets/576484/6251931/126dd854-b797-11e4-89a0-c69e649a08a4.jpg)

**Comment by Aetherwrath** [comment]
Already removed. I also made the sprite order how it goes. Thanks. Uploading the new file


![sprite orde](https://cloud.githubusercontent.com/assets/10867039/6253098/00da3260-b76d-11e4-8bd3-71deea9f7ccd.JPG)

**Comment by Leunam** [comment]
This is what I mean
![structure-style2](https://cloud.githubusercontent.com/assets/576484/6254058/0573e65c-b7a6-11e4-8b14-ca0cd20cfb58.jpg)
If you can create another graphic without the structure painted in red then we can create different GameObjects with different shapes so the user has more variety ingame.
With the current graphic the User has the feel of being in the same place all the time or the feeling of no Stage progression.
The idea is to display different shapes at random.

**Comment by Leunam** [comment]
Fixed
