### ISSUE TITLE
Lifemeter could shrink itself to accomodate to the amount of current energy.

### ISSUE THREAD

**Issue by bochelord** [radicalgraphics/IterRad#8]
The lifemeter has space for 10 energy levels. If we shrink the graphic based on the current amount of energy bars that you have, we could get less HUD problems...
This is something we need to think about. Comment if you have ideas guys...
![lifemeter_shriking](https://cloud.githubusercontent.com/assets/3027503/6375418/3c910054-bd17-11e4-8e64-6b5f7c13aebd.jpg)

**Comment by Leunam** [comment]
Won't fix. by design.
